import { Inter } from "next/font/google";
import "./globals.css";
import clsx from "clsx";
import StardustBackground from "./components/StardustBackground";

const inter = Inter({ 
  subsets: ["latin"], 
  variable: "--font-inter"
 });

export const metadata = {
  title: "Qetsia Nkulu",
  description: "Generated by create next app",
  icons: { 
    icon: "/qetsiankulu-favicon.svg",
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={clsx(inter.variable, "bg-background text-foreground")}>
        {children}
        <StardustBackground/>
        
        </body>
    </html>
  );
}
